const data = [
  {
    id: 1,
    brand: "Fender",
    make: "American Professional II",
    model: "Precision Bass",
    year: 2021,
    color: "3-Color Sunburst",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 1699,
    image_link:
      "https://www.fender.com/cdn-cgi/image/format=auto,resize=height=auto,width=1500/https://www.fmicassets.com/Damroot/eCommPNG/10001/0193930700_fen_ins_frt_1_rr.png",
  },
  {
    id: 2,
    brand: "Gibson",
    make: "Original Collection",
    model: "EB-0",
    year: 1972,
    color: "Cherry Red",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 2200,
    image_link:
      "https://www.gibson.com/cdn/shop/files/BSGSEB0EBCH1_front.png?v=1745526287&width=823",
  },
  {
    id: 3,
    brand: "Ibanez",
    make: "SR Series",
    model: "SR500E",
    year: 2023,
    color: "Brown Mahogany",
    string_number: 5,
    form_factor: "solid body",
    number_of_frets: 24,
    price: 849,
    image_link:
      "https://www.ibanez.com/common/product_artist_file/file/p_region_SR500E_BM_1P_04.png",
  },
  {
    id: 4,
    brand: "Music Man",
    make: "StingRay",
    model: "StingRay Special",
    year: 2022,
    color: "Gloss Black",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 22,
    price: 2399,
    image_link:
      "https://s3-us-west-2.amazonaws.com/static.music-man.com/website/images/instruments/instrument-74.png?1749573193",
  },
  {
    id: 5,
    brand: "Yamaha",
    make: "BB Series",
    model: "BB734A",
    year: 2020,
    color: "Matte Black",
    string_number: 5,
    form_factor: "solid body",
    number_of_frets: 21,
    price: 849,
    image_link:
      "https://usa.yamaha.com/files/BB734A_DCS_f_0001_from_bb734a_dcs_ae57c7aac55ae2fe3a7cf1a9f0f72490.jpg?impolicy=resize&imwid=735&imhei=735",
  },
  {
    id: 6,
    brand: "Warwick",
    make: "RockBass",
    model: "Corvette Basic",
    year: 2019,
    color: "Nirvana Black Transparent Satin",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 24,
    price: 999,
    image_link:
      "https://www.warwickbass.com/warwick/data/Warwick.de/Warwick/China/Rock_Bass/Basic%208%20strings/1508030300CAALDAWW_02.jpg",
  },
  {
    id: 7,
    brand: "Squier",
    make: "Classic Vibe",
    model: "Jazz Bass '60s",
    year: 2021,
    color: "Olympic White",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 449,
    image_link:
      "https://www.fender.com/cdn-cgi/image/format=auto,resize=height=auto,width=1500/https://www.fmicassets.com/Damroot/eCommPNG/10066/0374530511_sqr_ins_frt_1_rr.png",
  },
  {
    id: 8,
    brand: "Rickenbacker",
    make: "Standard",
    model: "4003",
    year: 2018,
    color: "Jetglo",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 2599,
    image_link:
      "https://www.rickenbacker.com/wp-content/uploads/2024/02/4003-JG.jpg.webp",
  },
  {
    id: 9,
    brand: "ESP",
    make: "LTD B Series",
    model: "B-206SM",
    year: 2024,
    color: "Natural Satin",
    string_number: 6,
    form_factor: "solid body",
    number_of_frets: 24,
    price: 699,
    image_link:
      "https://cdn.connectsites.net/user_files/esp/product_images/000/026/154/original.png?1741808346",
  },
  {
    id: 10,
    brand: "Schecter",
    make: "Stiletto Series",
    model: "Stiletto Studio-5",
    year: 2022,
    color: "Honey Satin",
    string_number: 5,
    form_factor: "solid body",
    number_of_frets: 24,
    price: 1199,
    image_link:
      "https://www.schecterguitars.com/images/Stiletto%20Studio-5.See-Thru%20Black%20Satin%20(STBLS).01.png",
  },
  {
    id: 11,
    brand: "Fender",
    make: "Player Plus",
    model: "Jazz Bass V",
    year: 2023,
    color: "Belair Blue",
    string_number: 5,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 1249,
    image_link:
      "https://www.fender.com/cdn-cgi/image/format=auto,resize=height=auto,width=1500/https://www.fmicassets.com/Damroot/eCommPNG/10001/0374550506_gtr_frt_001_rr.png",
  },
  {
    id: 12,
    brand: "Ibanez",
    make: "Talman Bass",
    model: "TMB100",
    year: 2021,
    color: "Mint Green",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 249,
    image_link:
      "https://www.ibanez.com/common/product_artist_file/file/p_region_TMB100_BK_1P_05_sub_3.jpg",
  },
  {
    id: 13,
    brand: "G&L",
    make: "Fullerton Deluxe",
    model: "LB-100",
    year: 2020,
    color: "Emerald Blue",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 21,
    price: 1599,
    image_link:
      "https://glguitars.com/upload/iblock/126/0028yyv3smjihf5jdjull4i9jhyzd3n2.jpg",
  },
  {
    id: 14,
    brand: "Dean",
    make: "Edge Series",
    model: "Edge 09",
    year: 2022,
    color: "Black",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 22,
    price: 199,
    image_link:
      "https://armadillo.sirv.com/assets/web/feature/e09cbk.png?w=1800&format=webp&q=80&subsampling=4:2:0",
  },
  {
    id: 15,
    brand: "Cort",
    make: "GB Series",
    model: "GB74JJ",
    year: 2021,
    color: "Natural",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 21,
    price: 749,
    image_link:
      "https://i0.wp.com/www.notreble.com/wp-content/uploads/2017/06/Cort-GB74JJ-Bass.jpg?w=2000&ssl=1",
  },
  {
    id: 16,
    brand: "Sire",
    make: "Marcus Miller Series",
    model: "V7 Vintage",
    year: 2022,
    color: "Tobacco Sunburst",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 20,
    price: 699,
    image_link:
      "https://www.sire-usa.com/cdn/shop/files/V7_VINTAGE_SWAMP_ASH_4_NT_1.png?v=1750304911&width=750",
  },
  {
    id: 17,
    brand: "Epiphone",
    make: "Jack Casady Signature",
    model: "Signature Bass",
    year: 2020,
    color: "Metallic Gold",
    string_number: 4,
    form_factor: "semi-hollow",
    number_of_frets: 20,
    price: 849,
    image_link:
      "https://cdn.long-mcquade.com/files/212876/lg_985fd12e5b2ab615f7caa0eaba174da5.jpg",
  },
  {
    id: 18,
    brand: "Peavey",
    make: "Grind Bass",
    model: "6 NTB",
    year: 2019,
    color: "Natural",
    string_number: 6,
    form_factor: "solid body",
    number_of_frets: 24,
    price: 599,
    image_link:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSb92lRKeeAdEv3-IoSVLDD3Yi4KWJ3ufQKL01dSvlUtA2GGPF-P7dhWYzIMu8LIhJLZvAoe8Is5lldqjdSbBS8Pxf78kaWUg",
  },
  {
    id: 19,
    brand: "Höfner",
    make: "Ignition Series",
    model: "Violin Bass",
    year: 2021,
    color: "Sunburst",
    string_number: 4,
    form_factor: "hollow body",
    number_of_frets: 22,
    price: 449,
    image_link:
      "https://cdn.long-mcquade.com/files/374568/xl_3ccf4c9264c4362e438e315a9e5bdd4f.webp?alt=Basse%20Violin%A0CT%20(fini%20Sunburst)",
  },
  {
    id: 20,
    brand: "Sandberg",
    make: "California TM",
    model: "TM4",
    year: 2023,
    color: "Soft Aged Candy Apple Red",
    string_number: 4,
    form_factor: "solid body",
    number_of_frets: 22,
    price: 2099,
    image_link:
      "https://www.stars-music.be/medias/sandberg/cropped-california-tm4-superlight-ltd-active-pf-44491-204359.webp",
  },
];
export default data;
